import { RouteRecordRaw } from 'vue-router';

const layout = () => import('/@/layout/index.vue');
const parentView = () => import('/@/layout/routerView/parent.vue');
const placeholderView = () => import('/@/views/tools/index.vue');
const salesReportView = () => import('/@/views/sales/report/index.vue');

const menuMeta = (title: string, icon: string, roles: string[] = ['admin', 'common']) => ({
	title,
	isLink: '',
	isHide: false,
	isKeepAlive: true,
	isAffix: false,
	isIframe: false,
	roles,
	icon,
});

export const dynamicRoutes: Array<RouteRecordRaw> = [
	{
		path: '/',
		name: 'root',
		component: layout,
		redirect: '/sales/report',
		meta: { isKeepAlive: true },
		children: [
			{
				path: '/sales',
				name: 'sales',
				component: parentView,
				redirect: '/sales/report',
				meta: menuMeta('销售', 'ele-Sell'),
				children: [
					{ path: '/sales/report', name: 'salesReport', component: salesReportView, meta: menuMeta('订单报表', 'ele-Files') },
					{ path: '/sales/order', name: 'salesOrder', component: placeholderView, meta: menuMeta('销售单', 'ele-Tickets') },
					{ path: '/sales/business', name: 'salesBusiness', component: placeholderView, meta: menuMeta('业务单', 'ele-Link') },
					{ path: '/sales/progress', name: 'salesProgress', component: placeholderView, meta: menuMeta('销售进度', 'ele-Connection') },
					{ path: '/sales/duplicate-order', name: 'salesDuplicateOrder', component: placeholderView, meta: menuMeta('翻单', 'ele-DocumentCopy') },
					{ path: '/sales/order-report', name: 'salesOrderReport', component: placeholderView, meta: menuMeta('销售报表', 'ele-Document') },
					{ path: '/sales/order-analysis', name: 'salesOrderAnalysis', component: placeholderView, meta: menuMeta('订单分析表', 'ele-Histogram') },
					{ path: '/sales/customer-analysis', name: 'salesCustomerAnalysis', component: placeholderView, meta: menuMeta('客户分析表', 'ele-DataAnalysis') },
					{ path: '/sales/product-list', name: 'salesProductList', component: placeholderView, meta: menuMeta('销售产品清单', 'ele-List') },
					{ path: '/sales/analysis-report', name: 'salesAnalysisReport', component: placeholderView, meta: menuMeta('销售分析表', 'ele-PieChart') },
	
					{ path: '/sales/invoice-record', name: 'salesInvoiceRecord', component: placeholderView, meta: menuMeta('销售开票记录', 'ele-DocumentChecked') },
					{ path: '/sales/customer-balance', name: 'salesCustomerBalance', component: placeholderView, meta: menuMeta('客户余额统计', 'ele-Coin') },
					{ path: '/sales/customer-reconciliation', name: 'salesCustomerReconciliation', component: placeholderView, meta: menuMeta('客户对账统计', 'ele-Postcard') },
					{ path: '/sales/arrears', name: 'salesArrears', component: placeholderView, meta: menuMeta('欠款统计', 'ele-Warning') },
					{ path: '/sales/price-lookup', name: 'salesPriceLookup', component: placeholderView, meta: menuMeta('价格速查', 'ele-Search') },
					{
						path: '/sales/delivery-return',
						name: 'salesDeliveryReturn',
						component: parentView,
						redirect: '/sales/delivery-return/delivery',
						meta: menuMeta('发货退货管理', 'ele-Box'),
						children: [
							{ path: '/sales/delivery-return/delivery', name: 'salesDelivery', component: placeholderView, meta: menuMeta('发货', 'ele-Van') },
							{ path: '/sales/delivery-return/product-return', name: 'salesProductReturn', component: placeholderView, meta: menuMeta('产品退货', 'ele-RefreshLeft') },
							{ path: '/sales/delivery-return/freight-report', name: 'salesFreightReport', component: placeholderView, meta: menuMeta('运费报表', 'ele-DataLine') },
						],
					},
					{
						path: '/sales/after-sales',
						name: 'salesAfterSales',
						component: parentView,
						redirect: '/sales/after-sales/complaint',
						meta: menuMeta('售后管理', 'ele-Service'),
						children: [
							{ path: '/sales/after-sales/complaint', name: 'salesComplaint', component: placeholderView, meta: menuMeta('客户投诉', 'ele-ChatLineRound') },
							{ path: '/sales/after-sales/satisfaction', name: 'salesSatisfaction', component: placeholderView, meta: menuMeta('客户满意度', 'ele-Star') },
						],
					},
				],
			},
			{
				path: '/purchase',
				name: 'purchase',
				component: parentView,
				redirect: '/purchase/order',
				meta: menuMeta('采购', 'ele-ShoppingCart'),
				children: [
					{ path: '/purchase/order', name: 'purchaseOrder', component: placeholderView, meta: menuMeta('采购单', 'ele-Document') },
					{ path: '/purchase/product-list', name: 'purchaseProductList', component: placeholderView, meta: menuMeta('采购产品清单', 'ele-List') },
					{ path: '/purchase/report', name: 'purchaseReport', component: placeholderView, meta: menuMeta('采购报表', 'ele-Files') },
					{ path: '/purchase/invoice-list', name: 'purchaseInvoiceList', component: placeholderView, meta: menuMeta('采购开票列表', 'ele-DocumentChecked') },
					{ path: '/purchase/invoice-product-list', name: 'purchaseInvoiceProductList', component: placeholderView, meta: menuMeta('开票产品清单', 'ele-CollectionTag') },
					{ path: '/purchase/invoice-summary', name: 'purchaseInvoiceSummary', component: placeholderView, meta: menuMeta('开票汇总表', 'ele-DataAnalysis') },
					{ path: '/purchase/request-order', name: 'purchaseRequestOrder', component: placeholderView, meta: menuMeta('请购单', 'ele-Tickets') },
					{ path: '/purchase/request-product-list', name: 'purchaseRequestProductList', component: placeholderView, meta: menuMeta('请购产品清单', 'ele-List') },
					{ path: '/purchase/material-status-query', name: 'purchaseMaterialStatusQuery', component: placeholderView, meta: menuMeta('物料加权查询', 'ele-Search') },
					{
						path: '/purchase/supplier-management',
						name: 'purchaseSupplierManagement',
						component: parentView,
						redirect: '/purchase/supplier-management/info',
						meta: menuMeta('供应商管理', 'ele-Management'),
						children: [
							{ path: '/purchase/supplier-management/info', name: 'purchaseSupplierInfo', component: placeholderView, meta: menuMeta('供应商信息', 'ele-Menu') },
							{ path: '/purchase/supplier-management/category', name: 'purchaseSupplierCategory', component: placeholderView, meta: menuMeta('供应商分类', 'ele-Link') },
						],
					},
				],
			},
			{
				path: '/production',
				name: 'production',
				component: parentView,
				redirect: '/production/process-card-review/production-order',
				meta: menuMeta('生产', 'ele-Operation'),
				children: [
					{
						path: '/production/process-card-review',
						name: 'productionProcessCardReview',
						component: parentView,
						redirect: '/production/process-card-review/production-order',
						meta: menuMeta('工艺卡审核', 'ele-Select'),
						children: [
							{ path: '/production/process-card-review/production-order', name: 'productionOrder', component: placeholderView, meta: menuMeta('生产单', 'ele-Menu') },
							{ path: '/production/process-card-review/process-transfer-card', name: 'productionProcessTransferCard', component: placeholderView, meta: menuMeta('工艺流转卡', 'ele-Postcard') },
						],
					},
					{ path: '/production/workbench-report', name: 'productionWorkbenchReport', component: placeholderView, meta: menuMeta('工作台报工信息', 'ele-Connection') },
					{ path: '/production/plan-board', name: 'productionPlanBoard', component: placeholderView, meta: menuMeta('生产计划看板', 'ele-Monitor') },
					{ path: '/production/tracing-info', name: 'productionTracingInfo', component: placeholderView, meta: menuMeta('生产追溯信息', 'ele-Clock') },
					{ path: '/production/worker-report', name: 'productionWorkerReport', component: placeholderView, meta: menuMeta('工人生产报表', 'ele-User') },
					{ path: '/production/process-report-record', name: 'productionProcessReportRecord', component: placeholderView, meta: menuMeta('工序报工记录', 'ele-Link') },
				],
			},
			{
				path: '/laboratory',
				name: 'laboratory',
				component: parentView,
				redirect: '/laboratory/calculation',
				meta: menuMeta('实验', 'ele-MagicStick'),
				children: [
					{ path: '/laboratory/calculation', name: 'laboratoryCalculation', component: placeholderView, meta: menuMeta('实验测算', 'ele-EditPen') },
				],
			},
			{
				path: '/quality',
				name: 'quality',
				component: parentView,
				redirect: '/quality/inspection',
				meta: menuMeta('质量', 'ele-Select'),
				children: [
					{ path: '/quality/inspection', name: 'qualityInspection', component: placeholderView, meta: menuMeta('质检', 'ele-Checked') },
					{ path: '/quality/management', name: 'qualityManagement', component: placeholderView, meta: menuMeta('质量管理', 'ele-Management') },
					{ path: '/quality/incoming-inspection', name: 'qualityIncomingInspection', component: placeholderView, meta: menuMeta('来料检验', 'ele-Document') },
				],
			},
			{
				path: '/warehouse',
				name: 'warehouse',
				component: parentView,
				redirect: '/warehouse/product-management/product-data',
				meta: menuMeta('仓储', 'ele-Box'),
				children: [
					{
						path: '/warehouse/product-management',
						name: 'warehouseProductManagement',
						component: parentView,
						redirect: '/warehouse/product-management/product-data',
						meta: menuMeta('产品管理', 'ele-Box'),
						children: [
							{ path: '/warehouse/product-management/product-data', name: 'warehouseProductData', component: placeholderView, meta: menuMeta('产品资料表', 'ele-SetUp') },
							{ path: '/warehouse/product-management/product-category', name: 'warehouseProductCategory', component: placeholderView, meta: menuMeta('产品分类', 'ele-Files') },
						],
					},
					{
						path: '/warehouse/inout-management',
						name: 'warehouseInoutManagement',
						component: parentView,
						redirect: '/warehouse/inout-management/purchase-inbound',
						meta: menuMeta('出入库管理', 'ele-Sort'),
						children: [
							{ path: '/warehouse/inout-management/purchase-inbound', name: 'warehousePurchaseInbound', component: placeholderView, meta: menuMeta('采购入库', 'ele-Link') },
							{ path: '/warehouse/inout-management/inbound', name: 'warehouseInbound', component: placeholderView, meta: menuMeta('入库', 'ele-Download') },
							{ path: '/warehouse/inout-management/other-inbound', name: 'warehouseOtherInbound', component: placeholderView, meta: menuMeta('其他入库', 'ele-Link') },
							{ path: '/warehouse/inout-management/outbound', name: 'warehouseOutbound', component: placeholderView, meta: menuMeta('出库', 'ele-Link') },
							{ path: '/warehouse/inout-management/other-outbound', name: 'warehouseOtherOutbound', component: placeholderView, meta: menuMeta('其他出库', 'ele-Link') },
							{ path: '/warehouse/inout-management/project-outbound', name: 'warehouseProjectOutbound', component: placeholderView, meta: menuMeta('工程单出库', 'ele-Link') },
							{ path: '/warehouse/inout-management/project-return', name: 'warehouseProjectReturn', component: placeholderView, meta: menuMeta('工程单退货', 'ele-Link') },
							{ path: '/warehouse/inout-management/production-data', name: 'warehouseProductionData', component: placeholderView, meta: menuMeta('生产资料', 'ele-Link') },
							{ path: '/warehouse/inout-management/transfer-inout', name: 'warehouseTransferInout', component: placeholderView, meta: menuMeta('调拨出入库', 'ele-Link') },
						],
					},
					{
						path: '/warehouse/report-query',
						name: 'warehouseReportQuery',
						component: parentView,
						redirect: '/warehouse/report-query/inout-summary',
						meta: menuMeta('报表查询', 'ele-Search'),
						children: [
							{ path: '/warehouse/report-query/inout-summary', name: 'warehouseInoutSummary', component: placeholderView, meta: menuMeta('出入库汇总查询', 'ele-Menu') },
							{ path: '/warehouse/report-query/inventory-report', name: 'warehouseInventoryReport', component: placeholderView, meta: menuMeta('库存报表', 'ele-Globe') },
							{ path: '/warehouse/report-query/inventory-fast-search', name: 'warehouseInventoryFastSearch', component: placeholderView, meta: menuMeta('库存速查', 'ele-Link') },
							{ path: '/warehouse/report-query/package-inventory', name: 'warehousePackageInventory', component: placeholderView, meta: menuMeta('包装产品库存', 'ele-Link') },
							{ path: '/warehouse/report-query/inventory-adjust-record', name: 'warehouseInventoryAdjustRecord', component: placeholderView, meta: menuMeta('库存调整记录', 'ele-Link') },
							{ path: '/warehouse/report-query/material-outbound-summary', name: 'warehouseMaterialOutboundSummary', component: placeholderView, meta: menuMeta('材料出库汇总', 'ele-Link') },
						],
					},
					{ path: '/warehouse/inventory-analysis', name: 'warehouseInventoryAnalysis', component: placeholderView, meta: menuMeta('库存分析表', 'ele-DataAnalysis') },
					{ path: '/warehouse/warehouse-analysis', name: 'warehouseWarehouseAnalysis', component: placeholderView, meta: menuMeta('仓储分析', 'ele-Histogram') },
				],
			},
			{
				path: '/equipment',
				name: 'equipment',
				component: parentView,
				redirect: '/equipment/maintenance-record',
				meta: menuMeta('设备', 'ele-Opportunity'),
				children: [
					{ path: '/equipment/maintenance-record', name: 'equipmentMaintenanceRecord', component: placeholderView, meta: menuMeta('设备保养记录', 'ele-Tools') },
					{ path: '/equipment/risk-control-record', name: 'equipmentRiskControlRecord', component: placeholderView, meta: menuMeta('风险管控记录', 'ele-Warning') },
					{ path: '/equipment/gantt', name: 'equipmentGantt', component: placeholderView, meta: menuMeta('甘特图', 'ele-DataLine') },
				],
			},
			{
				path: '/kanban',
				name: 'kanban',
				component: parentView,
				redirect: '/kanban/equipment',
				meta: menuMeta('看板', 'ele-DataBoard'),
				children: [
					{ path: '/kanban/equipment', name: 'kanbanEquipment', component: placeholderView, meta: menuMeta('设备管理看板', 'ele-Monitor') },
					{ path: '/kanban/summary', name: 'kanbanSummary', component: placeholderView, meta: menuMeta('综合看板', 'ele-PieChart') },
				],
			},
			{
				path: '/finance',
				name: 'finance',
				component: parentView,
				redirect: '/finance/receipt-order',
				meta: menuMeta('财务', 'ele-Money'),
				children: [
					{ path: '/finance/receipt-order', name: 'financeReceiptOrder', component: placeholderView, meta: menuMeta('收款单', 'ele-EditPen') },
					{ path: '/finance/other-receivable', name: 'financeOtherReceivable', component: placeholderView, meta: menuMeta('其他应收', 'ele-Link') },
					{ path: '/finance/payment-order', name: 'financePaymentOrder', component: placeholderView, meta: menuMeta('付款单', 'ele-EditPen') },
					{ path: '/finance/other-payable', name: 'financeOtherPayable', component: placeholderView, meta: menuMeta('其他应付', 'ele-Link') },
					{ path: '/finance/write-off', name: 'financeWriteOff', component: placeholderView, meta: menuMeta('往来冲销单', 'ele-Link') },
					{ path: '/finance/receivable-balance', name: 'financeReceivableBalance', component: placeholderView, meta: menuMeta('应收余额表', 'ele-Link') },
					{ path: '/finance/payable-balance', name: 'financePayableBalance', component: placeholderView, meta: menuMeta('应付余额表', 'ele-Link') },
					{ path: '/finance/receivable-detail', name: 'financeReceivableDetail', component: placeholderView, meta: menuMeta('应收明细表', 'ele-Link') },
					{ path: '/finance/payable-detail', name: 'financePayableDetail', component: placeholderView, meta: menuMeta('应付明细表', 'ele-Link') },
					{ path: '/finance/receivable-aging', name: 'financeReceivableAging', component: placeholderView, meta: menuMeta('应收账龄分析表', 'ele-Link') },
					{ path: '/finance/payable-aging', name: 'financePayableAging', component: placeholderView, meta: menuMeta('应付账龄分析表', 'ele-Link') },
					{ path: '/finance/receivable-current-account', name: 'financeReceivableCurrentAccount', component: placeholderView, meta: menuMeta('应收往来对账单', 'ele-Link') },
					{ path: '/finance/payable-current-account', name: 'financePayableCurrentAccount', component: placeholderView, meta: menuMeta('应付往来对账单', 'ele-Link') },
					{ path: '/finance/cost-accounting', name: 'financeCostAccounting', component: placeholderView, meta: menuMeta('成本核算', 'ele-Link') },
					{ path: '/finance/cash-bank-journal', name: 'financeCashBankJournal', component: placeholderView, meta: menuMeta('现金银行日记账', 'ele-Link') },
					{ path: '/finance/expense-category', name: 'financeExpenseCategory', component: placeholderView, meta: menuMeta('支出类别管理', 'ele-Link') },
					{ path: '/finance/expense-payable', name: 'financeExpensePayable', component: placeholderView, meta: menuMeta('应支出', 'ele-EditPen') },
					{ path: '/finance/expense-analysis', name: 'financeExpenseAnalysis', component: placeholderView, meta: menuMeta('支出分析表', 'ele-Link') },
					{ path: '/finance/asset-change', name: 'financeAssetChange', component: placeholderView, meta: menuMeta('资产变动单', 'ele-Link') },
					{ path: '/finance/production-apportionment', name: 'financeProductionApportionment', component: placeholderView, meta: menuMeta('生产分摊单', 'ele-Link') },
				],
			},
			{
				path: '/settings',
				name: 'settings',
				component: parentView,
				redirect: '/settings/system-user',
				meta: menuMeta('设置', 'ele-Setting'),
				children: [
					{ path: '/settings/system-user', name: 'settingsSystemUser', component: placeholderView, meta: menuMeta('系统用户', 'ele-User') },
					{
						path: '/settings/basic-definition',
						name: 'settingsBasicDefinition',
						component: parentView,
						redirect: '/settings/basic-definition/customer-category',
						meta: menuMeta('基础数据定义', 'ele-Collection'),
						children: [
							{ path: '/settings/basic-definition/customer-category', name: 'settingsCustomerCategory', component: placeholderView, meta: menuMeta('客户分类', 'ele-Link') },
							{ path: '/settings/basic-definition/customer-info', name: 'settingsCustomerInfo', component: placeholderView, meta: menuMeta('客户信息', 'ele-User') },
							{ path: '/settings/basic-definition/supplier-info', name: 'settingsSupplierInfo', component: placeholderView, meta: menuMeta('供应商信息', 'ele-Van') },
							{ path: '/settings/basic-definition/unit-management', name: 'settingsUnitManagement', component: placeholderView, meta: menuMeta('计量单位管理', 'ele-Link') },
							{ path: '/settings/basic-definition/vehicle-setting', name: 'settingsVehicleSetting', component: placeholderView, meta: menuMeta('车辆设置', 'ele-Van') },
							{ path: '/settings/basic-definition/company-info', name: 'settingsCompanyInfo', component: placeholderView, meta: menuMeta('公司信息设置', 'ele-Link') },
							{ path: '/settings/basic-definition/industry-category', name: 'settingsIndustryCategory', component: placeholderView, meta: menuMeta('行业类别', 'ele-Link') },
							{ path: '/settings/basic-definition/currency-setting', name: 'settingsCurrencySetting', component: placeholderView, meta: menuMeta('币种设置', 'ele-Link') },
							{ path: '/settings/basic-definition/warehouse-category', name: 'settingsWarehouseCategory', component: placeholderView, meta: menuMeta('仓库分类设置', 'ele-Link') },
							{ path: '/settings/basic-definition/warehouse-setting', name: 'settingsWarehouseSetting', component: placeholderView, meta: menuMeta('仓库设置', 'ele-House') },
							{ path: '/settings/basic-definition/process-setting', name: 'settingsProcessSetting', component: placeholderView, meta: menuMeta('工序设置', 'ele-Setting') },
							{ path: '/settings/basic-definition/repair-project', name: 'settingsRepairProject', component: placeholderView, meta: menuMeta('维修项目设置', 'ele-Link') },
							{ path: '/settings/basic-definition/asset-management', name: 'settingsAssetManagement', component: placeholderView, meta: menuMeta('资产管理', 'ele-Link') },
							{ path: '/settings/basic-definition/inout-type', name: 'settingsInoutType', component: placeholderView, meta: menuMeta('出入库类型', 'ele-Link') },
							{ path: '/settings/basic-definition/production-equipment', name: 'settingsProductionEquipment', component: placeholderView, meta: menuMeta('生产设备管理', 'ele-Setting') },
							{ path: '/settings/basic-definition/workshop-setting', name: 'settingsWorkshopSetting', component: placeholderView, meta: menuMeta('车间设置', 'ele-Box') },
							{ path: '/settings/basic-definition/bank-account', name: 'settingsBankAccount', component: placeholderView, meta: menuMeta('银行账户', 'ele-OfficeBuilding') },
						],
					},
					{ path: '/settings/user-management', name: 'settingsUserManagement', component: placeholderView, meta: menuMeta('用户管理', 'ele-User') },
					{ path: '/settings/message-management', name: 'settingsMessageManagement', component: placeholderView, meta: menuMeta('消息管理', 'ele-Bell') },
					{ path: '/settings/system-log', name: 'settingsSystemLog', component: placeholderView, meta: menuMeta('系统日志', 'ele-Document') },
				],
			},
		],
	},
];

export const notFoundAndNoPower: Array<RouteRecordRaw> = [
	{
		path: '/:path(.*)*',
		name: 'notFound',
		component: () => import('/@/views/error/404.vue'),
		meta: { title: '404', isHide: true },
	},
	{
		path: '/401',
		name: 'noPower',
		component: () => import('/@/views/error/401.vue'),
		meta: { title: '401', isHide: true },
	},
];

export const staticRoutes: Array<RouteRecordRaw> = [
	{
		path: '/login',
		name: 'login',
		component: () => import('/@/views/login/index.vue'),
		meta: { title: '登录' },
	},
];
